#ifndef _TL_TYPE_TRAITS_H
#define _TL_TYPE_TRAITS_H


#include "type_traits/add_const.h"
#include "type_traits/add_cv.h"
#include "type_traits/add_lvalue_reference.h"
#include "type_traits/add_pointer.h"
#include "type_traits/add_reference.h"
#include "type_traits/add_rvalue_reference.h"
#include "type_traits/add_volatile.h"

#include "type_traits/arifhmetic_traits.h"
#include "type_traits/array_traits.h"
#include "type_traits/common_type.h"            
#include "type_traits/conditional.h"
#include "type_traits/copy_cv.h"
#include "type_traits/copy_cv_ref.h"
#include "type_traits/copy_reference.h"
#include "type_traits/cv_traits.h"
#include "type_traits/decay.h"
#include "type_traits/enable_if.h"
#include "type_traits/function_traits.h"

#include "type_traits/is_arifhmetic.h"
#include "type_traits/is_array.h"
#include "type_traits/integral_constants.h"
#include "type_traits/is_complete.h"                 
#include "type_traits/is_class.h"                 
#include "type_traits/is_const.h"
#include "type_traits/is_cv.h"
#include "type_traits/is_default_constructible.h"
#include "type_traits/is_float.h"
#include "type_traits/is_function.h"
#include "type_traits/is_fundamental.h"
#include "type_traits/is_integral.h"
#include "type_traits/is_lvalue_reference.h"
#include "type_traits/is_pointer.h"
#include "type_traits/is_reference.h"
#include "type_traits/is_rvalue_reference.h"
#include "type_traits/is_same.h"
#include "type_traits/is_void.h"
#include "type_traits/is_volatile.h"

#include "type_traits/make_void.h"
#include "type_traits/pointer_traits.h"
#include "type_traits/rank.h"
#include "type_traits/reference_traits.h"
#include "type_traits/remove_const.h"
#include "type_traits/remove_cv.h"
#include "type_traits/remove_cv_ref.h"
#include "type_traits/remove_extent.h"
#include "type_traits/remove_pointer.h"
#include "type_traits/remove_reference.h"
#include "type_traits/remove_volatile.h"
#include "type_traits/type_identity.h"

#endif//_TL_TYPE_TRAITS_H
